### ISSUE TITLE
LDAP: refactor the ldap synchronisation

### ISSUE THREAD

**Issue by netsensei** [ugent-library/people-service#2]
The ldap synchronizers can be refactored to make it a bit more readable, maintainable.

1/ SetPeopleActive => SetPersonActive

The `chunkList` logic seems to exist to offset potentially creating a massive `UPDATE` query due to use of the `any()` operator. The number of records that will be set to "false" won't number in the tens of thousands or more. I don't see a performance issue here, so it's okay to just loop over all `inactiveIds` and do a discrete update query for each person id.

Ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L165

2/ Move 3 blocks into a separate method.

You have 3 code blocks repeating the exact same logic which can be put into a separate method:

ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L238
ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L259
ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L285

Also: you can get rid of `depIds` and `facultyIds` and just use `orgIds` for both `ugentFaculty` and `departmentNumber`. Because, in the end, the logic merges both into the same slice anyway:

ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L222
ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L224
ref: https://github.com/ugent-library/people-service/blob/b2bb690ca958dbbac9d5576c4e5fc605e26d7155/ldapsync/ldapsync.go#L238

Also: you can now get rid of the separate `addDummyOrg` method. You can fold it in the method you just created which adds organizations to a person.

Quick wins:

* Don't pass a `cb func(string)` param to the `sync()` method. Add a `logger *zap.SugaredLogger` property to the `Synchronizer` struct, and initialize via the constructor in `ldapsync_cmd.go`. Then within `sync()` call via `si.logger.InfoF()`.

**Comment by nicolasfranck** [comment]
* https://github.com/ugent-library/people-service/commit/f07d79912f0a4082c336f232eebc726142eca36c: remove unneeded multi update query SetPeopleActive
* https://github.com/ugent-library/people-service/commit/6e591c81c6c6c08d31080e9d00a1561fdcffa846: moved logger into Synchronizer package. The list of arguments in the constructor is getting a bit long though. Left it like this for now.

About the other remarks:

* there are several ways organizations are added here, and yes repeated:
  * `depIds` and `facultyIds`. I guess I wanted to fallback to faculties when there were no departments (so that `else` would become an `else if`), but I agreed with @nics  to just add both of them always, even if the department is already part of the faculty mentioned. Will fix it
  * adding `UGent` for ugent employee: better to move upwards. I guess I wanted to keep this "logic" separate, so it would never get mixed with other code (and therefore harder to remove). But not yet the case here.
  * adding `UZGent` for uzgent employee: Same here. Better to move upwards

See https://github.com/ugent-library/people-service/commit/d20c14eba4f4cc02d455fa0ac2dc51d2d218590b
